name: Tests - Windows

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "MSVC"
            runs-on: windows-latest
            toolchain: ""
            test-command: ".\${{env.BUILD_TYPE}}\tests.exe"
          - name: "MinGW Cross-compile" 
            runs-on: ubuntu-latest
            toolchain: "-DCMAKE_TOOLCHAIN_FILE=toolchain-mingw64.cmake"
            test-command: "wine ./tests.exe"
    
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install MinGW (Linux only)
      if: matrix.runs-on == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y gcc-mingw-w64-x86-64-posix g++-mingw-w64-x86-64-posix wine

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{ matrix.toolchain }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ${{ matrix.test-command }}
