# .github/workflows/release.yaml
name: Release Build

on:
  release:
    types: [created]

jobs:
  build-release:
    strategy:
      matrix:
        include:
          - platform: linux
            artifact_name: linux-x86-64-avx2
          - platform: windows  
            artifact_name: windows-x86-64-avx2-mingw
    
    name: Build ${{ matrix.platform }}
    uses: ./.github/workflows/build-reusable.yaml
    with:
      platform: ${{ matrix.platform }}
      build_type: Release
      enable_tests: false
      enable_avx2: true
      artifact_name: ${{ matrix.artifact_name }}
      binary_name: admete

  upload-release-assets:
    name: Upload Release Assets
    needs: build-release
    runs-on: ubuntu-latest
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Prepare Release Assets
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        
        mkdir -p release
        
        # Rename artifacts with version
        for artifact_dir in artifacts/*/; do
          for file in "$artifact_dir"*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              # Insert version into filename
              if [[ "$filename" == *.exe ]]; then
                new_name="${filename%.exe}_${VERSION}.exe"
              else
                new_name="${filename}_${VERSION}"
              fi
              cp "$file" "release/$new_name"
            fi
          done
        done
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: release/*